# -*- coding: utf-8 -*-
"""Calculando_cetes_vs_gbm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PJm3VJJ0yr6ETY4EGdCgTqpgC__go1n9

##Estimado GBM+ Smartcash (8.75% a un mes hoy 10.09.23)
"""

import math as m

fondo = 10000

##Estimado GBM+ Smartcash (8.75% a un mes hoy 10.09.23) 
porcentaje_gbm = (.0875 / 360) 
porcentaje_gbm_D = round(porcentaje_gbm,5)

GBM = 0
for a in range(30):
  if GBM <= 0:
    GBM = fondo + (fondo *porcentaje_gbm_D)
  else:
    GBM = GBM + (GBM * porcentaje_gbm_D)

print("El valor a fin de mes sera de " + str(round(GBM,2)))

"""##Estimado Cetes 1 mes (11.19% a un mes hoy 10.09.23)"""

##Estimado Cetes 1 mes (11.19% a un mes hoy 10.09.23) 

porcentaje_mes = .1119 / 12
total_dinero_Cetes = fondo + (fondo * porcentaje_mes)
print("Dinero a fin de mes: " + str(round(total_dinero_Cetes, 2)))

"""##Diferencia Cetes vs GBM+

"""

##Diferencia Cetes vs GBM+
diferencia = total_dinero_Cetes - GBM
print("Diferencia de CETES vs GBM+: " + str(round(diferencia, 2)))

